### ISSUE TITLE
Between with dates

### ISSUE THREAD

**Issue by Saulolxx** [TRUEPIC/queryql#19]
Is there a way to create an between filter with dates?

**Comment by jstayton** [comment]
Hi Saulo,

You should be able to use a `between` filter, but I may have the validation too strict. Are you running into a validation error?

**Comment by Saulolxx** [comment]
> Hi Saulo,
> 
> You should be able to use a filter, but I may have the validation too strict. Are you running into a validation error?`between`

Yes, and even trying to change the type of validation I don't get success

**Comment by jstayton** [comment]
Hi Saulo,

This is fixed in v0.5.0 that I just released. Let me know if you have any issues. Thanks!
