### ISSUE TITLE
Question: How to handle joins?

### ISSUE THREAD

**Issue by nampas** [TRUEPIC/queryql#24]
Hello! queryql seems pretty useful, and we're considering using it for a service here at TpT.

Do you have any examples of what a Querier would look like if it were to support joins? It seems like the examples deal with single tables.

Say for example our database schema looks like this:
```
table foo {
   id int
   the_important_stuff string
}

table bar {
   id int
   foo_id int references(foo.id)
   type string
}
```
And let's say we want to fetch `foo` by looking at `bar.type`:
```
/foos?filter[bar.type]=APPLE
```
Is that going to require a custom querier function? Something like this:
```
  'filter:[bar.type]='(builder, { field, operator, value }) {
    return builder.innerJoin('bar', 'foo.id', 'bar.foo_id').where(field, operator, value);
  }
```

**Comment by jstayton** [comment]
Hey Nathan,

Thanks for the good question!

What I typically do is join all of the (potentially) necessary tables ahead of time. Something like:

```js
const querier = new ImageQuerier(
  req.query,
  knex('images')
    .select('images.*')
    .innerJoin('users', 'images.user_id', 'users.id')
    .innerJoin('metadata', 'images.id', 'metadata.image_id')
)
```

The downside is it does degrade performance a bit if you join a bunch of tables that aren't filtered on most of the time. But I'm usually OK with that trade-off.

Your example using a custom querier function would work as well, and it ensures that tables aren't joined if they're not filtered on. The downside is the amount of code starts to add up when you have more than a few filter fields from the joined table. (I'm also not totally sure if Knex prevents duplicate joins?)

In a previous iteration of QueryQL that I wrote for Ruby/Rails back in the day, I built in a mechanism to dynamically join tables when necessary. But that was a little easier with ActiveRecord. That said, I think it could be possible here, maybe just with a little more configuration for query builders like Knex that don't have as much knowledge of the schema.

Hope that helps! Let me know if you have any further questions or suggestions.

**Comment by nampas** [comment]
Hey Justin, appreciate that quick response! That is very helpful.

One possibility to avoid doing eager fetches when not necessary would be to have some kind of hook in the Querier, let's call it `beforeFilter`. It would take the parsed query (the data structure produced by `FilterParser`) and the builder, and return the builder. In that function, we could execute eager fetches for tables that are included in this particular query.
```
# Inside ImageQuerier

function beforeFilter(filterData, builder) {
  # Clumsy implementation but you'll hopefully get the idea
  const joined = new Set();
  return Object.keys(filterData).reduce((acc, k) => {
     const fieldTokens = k.split(':')[1].split('.');
     const tbl = fieldTokens[0];
     if (fieldTokens.length > 1 && !joined.includes(tbl) {
       joined.add(tbl);
       return builder.innerJoin(tbl, 'images.id', `${tbl}.image_id`);
     }
     return builder;
  }, builder);
} 
```

But, just throwing ideas around. I think what you've outlined here should work for us for now.

**Comment by jstayton** [comment]
A `beforeFilter` hook (and, really, hooks in general) is an interesting idea. That would open up uses beyond just handling joins.

My gut says joins are probably important enough to handle specifically. I'll keep noodling on this.

Closing for now, since you have enough to push forward. Thanks again!

**Comment by nampas** [comment]
Hey @jstayton , it looks like we may actually need something along the lines of run hooks sooner rather than later, to support the following use cases:
* emitting metrics that are tagged with the queried properties
* transforming camelCase query param strings to snake_case db column names
* supporting the join case

All three of these cases seem achievable with a `beforeFilter` hook as described above.
What are your thoughts on that? Happy to open a PR if that seems reasonable.

Thanks!

**Comment by jstayton** [comment]
Hey Nathan,

Sorry for the delay here!

I'm open to the idea, and would be interested in seeing a rough PR (don't worry about tests, unless you want to) to ensure I'm understanding how you're needing it to work.

Thanks!
