### ISSUE TITLE
Total number of rows with pagination

### ISSUE THREAD

**Issue by joris77** [TRUEPIC/queryql#25]
With pagination you often have to return two pieces of information. One is the data itself , the second is the total number of rows that would have been returned without pagination. Is there a feature or best practice to be able to return this second piece of information? I guess I can create a second count querier and share the filters with the querier that queries for the data.

**Comment by jstayton** [comment]
Hey Joris,

Here's what we do at Truepic:

```js
const querier = new YourQuerier(...)

const records = await querier.run()

const {
  totalCount,
} = await querier.builder
  .clone()
  .clearOrder()
  .clearSelect()
  .offset(0)
  .count('* as totalCount')
  .first()
```

I've thought about putting this into QueryQL itself, but it hasn't happened so far. It's good to know someone else would find it useful for future consideration.

Hope that helps!

**Comment by joris77** [comment]
Hi,

That helps a lot I was thinking of such a solution but yours looks nicer with the clear statements. Tnx for the quick reply and the work you did on this lib.

**Comment by jstayton** [comment]
I ran into some issues with my above example when the query was more complex (i.e., using `group by`, `having`).

Here's where I landed:

```js
const querier = new YourQuerier(...)

const records = await querier.run()

const { totalCount } = await knex
  .with(
    'records',
    querier.builder.clone().clear('order').clear('limit').clear('offset')
  )
  .count('* as totalCount')
  .from('records')
  .first()
```

This requires the latest version of Knex in order to use the new `clear` function.
