### ISSUE TITLE
How do you manage long query?

### ISSUE THREAD

**Issue by FPierre** [TRUEPIC/queryql#33]
Sometimes "batch" selection requires something like:

```
/images?filter[id][in][]=229303&filter[id][in][]=393093&filter[id][in][]=102933&filter[id][in][]=3993004&filter[id][in][]=192383....(more and more filters)
```

And will hit the [URL length limitation](https://www.xspdf.com/resolution/58038072.html)

So far, depends on the HTTP method, I prefer using the body to filter (e.g: on PUT `{ body: { filters: [...] } }`)
But how you advise to do it for GET method?

**Comment by jstayton** [comment]
Hey Pierre,

Yes, I've run into this myself once before. I ended up creating a `POST` version of the route to do exactly what you suggested: pass the query string in the body.

Another idea is using commas in the query string to separate array values. For example:

```
/images?filter[id][in][]=229303,393093,102933,3993004,192383
```

I know a few query string parsers support this syntax if enabled, such as qs ([see the last example here](https://github.com/ljharb/qs#parsing-arrays)).

Hope that helps!
