### ISSUE TITLE
React and IOS packages to create URL which support QueryQL operations

### ISSUE THREAD

**Issue by sandeshfromindia** [TRUEPIC/queryql#34]
Hi, i wanted help to find IOS packages to create query URL which will support QueryQL structure, also in React native and React JS, Thanks in advance

**Comment by jstayton** [comment]
Hey @sandeshfromindia,

For React and React Native, you can use a JS package like [qs](https://www.npmjs.com/package/qs) with these options:

```js
{
  arrayFormat: 'brackets',
  encode: false,
}
```

I'm not familiar with the iOS ecosystem, but most query string packages allow you to configure them to encode objects in the way QueryQL expects.

Let me know if you have any other questions!
