### ISSUE TITLE
Using queryql with Sequelize

### ISSUE THREAD

**Issue by twastvedt** [TRUEPIC/queryql#35]
Hi! This project looks great! I'm trying to work out how to use it with our app, which currently uses the Sequelize ORM. Am I right that Sequelize needs to have a query builder in order to make an adapter for it? Looks like it doesn't yet: https://github.com/sequelize/sequelize/issues/394. If not, any hints you might be able to provide on what SequelizeAdapter might need to look like would be awesome. Here's part of what I've been trying: 
```
'filter:*'(model, { field, operator, value }) {
        return model.findAll({
            where: {
                [field]: {
                    [this.operatorMap[operator]]: value,
                },
            },
        });
    }
```
But that returns the actual found elements, not a query builder, so I think that's not the right track?

**Comment by twastvedt** [comment]
OK. Slowly parsing through the code here. Now I think what I need to do is just pass that options object around as the "builder". The filters, sorter, and pager just add properties to the object. Then in a BaseQuerier I override QueryQL's run method and apply the options object to the Sequelize model. Maybe?

**Comment by jstayton** [comment]
Hey Trygve,

Thanks for the kind words!

> Now I think what I need to do is just pass that options object around as the "builder". The filters, sorter, and pager just add properties to the object.

Yes, I think you're on the right path with that. You're basically just building the object that's passed to `findAll`.

> Then in a BaseQuerier I override QueryQL's run method and apply the options object to the Sequelize model.

Yes, you could certainly do that if you want `run` to call `findAll`. You'd have to figure out how to pass the model in somehow, I think.

You could also just call `findAll` outside of QueryQL. Something like:

```js
const querier = new ImageQuerier(req.query, {})

const images = await Image.findAll(await querier.run())
```

Let me know how it all goes. I'd be interested in either including your Sequelize adapter class in this project, or linking to it if you decide to release it as a standalone package.
