### ISSUE TITLE
"Expected 0 arguments, but got 2" on class which extends QueryQL

### ISSUE THREAD

**Issue by johndanek** [TRUEPIC/queryql#42]
I am trying to get QueryQL to work with my Express + MikroORM app. MikroORM uses knex under the hood so I believe I should be able to get this to work without writing an adapter.

My Querier class looks like this:

```
import QueryQL from '@truepic/queryql';

export class ContentQuerier extends QueryQL {

  get pageDefaults() {
    return {
      size: 12
    };
  }

}
```

and I attempt to use this class in my route:

```
const queryBuilder = orm.em.createQueryBuilder(Content);
const query = req.query;
const querier = new ContentQuerier(query, queryBuilder);
```

but I get a TypeScript error on that final line, flagging the `query` and `queryBuilder` properties: `src/routes/records.ts:19:40 - error TS2554: Expected 0 arguments, but got 2.`

Any idea why TypeScript thinks the QueryQL consturctor doesn't have any parameters? Thanks!

**Comment by jstayton** [comment]
Hey John,

Hmmm. I don't have any TypeScript experience, unfortunately, so I don't really have any idea why it would think that. Are you able to introspect the class at all to see what TypeScript thinks is there?

For what it's worth, I also haven't tried QueryQL with ESM (`import`/`export`), though I don't have any reason to believe that it wouldn't just work.

**Comment by johndanek** [comment]
Good question. It appears that when I import QueryQL, that object is the following:

```
[Function: QueryQL] {
  adapters: {
    BaseAdapter: [Function: BaseAdapter],
    KnexAdapter: [Function: KnexAdapter]
  },
  Config: [Function: Config] {
    _defaults: {
      adapter: [Function: KnexAdapter],
      validator: [Function: JoiValidator]
    }
  },
  errors: {
    BaseError: [Function: BaseError],
    NotImplementedError: [Function: NotImplementedError],
    ValidationError: [Function: ValidationError]
  },
  validators: {
    BaseValidator: [Function: BaseValidator],
    JoiValidator: [Function: JoiValidator]
  }
}
```

Can't seem to get a reference to the actual class. I think for the short term, I'm going to proceed without QueryQL but if it ever becomes TypeScript-compatible I'll definitely give it another look!

**Comment by jstayton** [comment]
> For what it's worth, I also haven't tried QueryQL with ESM (`import`/`export`), though I don't have any reason to believe that it wouldn't just work.

I quickly tried `import QueryQL from '@truepic/queryql'` in an ESM project, and it worked fine. So, I don't think it's that.

I get this when I log `QueryQL`:

```
[class QueryQL] {
  adapters: {
    BaseAdapter: [class BaseAdapter],
    KnexAdapter: [class KnexAdapter extends BaseAdapter]
  },
  Config: [class Config] {
    _defaults: {
      adapter: [class KnexAdapter extends BaseAdapter],
      validator: [class JoiValidator extends BaseValidator]
    }
  },
  errors: {
    BaseError: [class BaseError extends Error],
    NotImplementedError: [class NotImplementedError extends BaseError],
    ValidationError: [class ValidationError extends BaseError]
  },
  validators: {
    BaseValidator: [class BaseValidator],
    JoiValidator: [class JoiValidator extends BaseValidator]
  }
}
```

It's strange that I get `Class` where you get `Function`, but maybe that's just a normal TypeScript thing.

I'm going to close this for now. If anyone with TypeScript knowledge comes across this and knows the answer, please chime in!
