### ISSUE TITLE
Koa's query doesn't support nested parsing

### ISSUE THREAD

**Issue by Turbotailz** [TRUEPIC/queryql#44]
Hey there, awesome project!
I just wanted to point out something that had me stuck for a couple of hours.

Koa's request object does not support nested parsing of the query string (it uses Node's native [querystring](https://nodejs.org/api/querystring.html)).

I had to install [qs](https://npmjs.org/package/qs) to parse the query string properly.

It could be a good idea to update the docs to make sure people know they need to provide the query object in the correct structure when dealing with nested data.

**Comment by jstayton** [comment]
Hey @Turbotailz,

Thanks for the kind words, and for pointing that out! Sorry it had you spinning your wheels for a bit.

I've added a note about it to the docs.
