### ISSUE TITLE
Typescript for QueryQL

### ISSUE THREAD

**Issue by NicolasGorga** [TRUEPIC/queryql#62]
Hello,

First of all, congratulations on writing (so far as i can tell) the only package that allows to easily manage filtering, sorting and paging in a clear way for REST APis.

I am developing a Typescript Express API that uses TypeORM as ORM. I know i can write an adapter for it and reading on how the Knex one is implemented it seems to be pretty straightforward.

The problem is that without having Typescript types, this turns to be a slow and potentially dangerous way to develop.

Are there ay plans on transforming this project to a Typescript project with types?

Cheers

**Comment by jstayton** [comment]
Hey @NicolasGorga – Thanks for the kind words! At this point, there are no plans to convert this project to TypeScript. That may not always be the case, but we don't use TypeScript enough ourselves to make it a worthwhile endeavor just yet.
